version:  "3.8"
services:
  backend:
    build: ./backend
    image: backend
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/usr/src/app
  frontend:
    build: ./frontend
    image: frontend
    ports:
      - "8000:8000"
    volumes:
      - ./frontend:/usr/src/app
